/*389. Find the Difference

    Total Accepted: 9409
    Total Submissions: 18799
    Difficulty: Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
public class Solution {
	public char FindTheDifference(string s, string t) {
		char c = (char)0;
		for (int i = 0; i < s.Length; ++i) {
			c ^= s[i]; /*stores all values*/
		}

		for (int i = 0; i < t.Length; ++i) {
			c ^= t[i]; /*To eliminate existing values  and leave the single value*/
		}

		return c;
	}
}


/*
JavaScript Solution
*/
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    if (s.length === 0) return t;
    var letters = 'abcdefghijklmnopqrstuvwxyz';
    var sSum = s.split('').map(e => e.charCodeAt(0) - 'a'.charCodeAt(0)).reduce((a, b) => a + b);
    var tSum = t.split('').map(e => e.charCodeAt(0) - 'a'.charCodeAt(0)).reduce((a, b) => a + b);
    return letters[tSum -sSum];
    
    /*Method 2
       //convert char to num, since xor operator will cast char to num
    let c = t.charCodeAt(t.length-1);           
    for(let i=0; i < s.length; i++){
        c = c ^ s.charCodeAt(i) ^ t.charCodeAt(i);
    }
    return String.fromCharCode(c);
    */
    
};